# Generated by Django 5.2.8 on 2025-11-05 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_ruta_parada_bus_tipoestado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='identificacion',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
