# Generated by Django 5.2.8 on 2025-11-05 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_identificacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parada',
            name='ruta',
        ),
        migrations.RemoveField(
            model_name='tipoestado',
            name='ruta',
        ),
        migrations.DeleteModel(
            name='Bus',
        ),
        migrations.DeleteModel(
            name='Parada',
        ),
        migrations.DeleteModel(
            name='Ruta',
        ),
        migrations.DeleteModel(
            name='TipoEstado',
        ),
    ]
