# Generated by Django 5.2.8 on 2025-11-05 22:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ruta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_ruta', models.CharField(max_length=100, verbose_name='Nombre de la ruta')),
                ('capacidad_activa', models.IntegerField(blank=True, null=True, verbose_name='Capacidad activa')),
                ('capacidad_espera', models.IntegerField(blank=True, null=True, verbose_name='Capacidad de espera')),
            ],
            options={
                'verbose_name': 'Ruta',
                'verbose_name_plural': 'Rutas',
            },
        ),
        migrations.CreateModel(
            name='Parada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_parada', models.CharField(max_length=100, verbose_name='Nombre de la parada')),
                ('direccion', models.CharField(max_length=150, verbose_name='Dirección')),
                ('tipo_punto', models.CharField(max_length=50, verbose_name='Tipo de punto')),
                ('ruta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paradas', to='rutas.ruta')),
            ],
            options={
                'verbose_name': 'Parada',
                'verbose_name_plural': 'Paradas',
            },
        ),
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=10, unique=True, verbose_name='Placa del bus')),
                ('marca', models.CharField(max_length=50, verbose_name='Marca del bus')),
                ('modelo', models.CharField(max_length=50, verbose_name='Modelo del bus')),
                ('capacidad', models.IntegerField(blank=True, null=True, verbose_name='Capacidad del bus')),
                ('estado_bus', models.CharField(max_length=50, verbose_name='Estado del bus')),
                ('ruta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buses', to='rutas.ruta')),
            ],
            options={
                'verbose_name': 'Bus',
                'verbose_name_plural': 'Buses',
            },
        ),
        migrations.CreateModel(
            name='TipoEstado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_estado', models.CharField(max_length=100, verbose_name='Nombre del estado')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción del estado')),
                ('ruta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tipos_estado', to='rutas.ruta')),
            ],
            options={
                'verbose_name': 'Tipo de Estado',
                'verbose_name_plural': 'Tipos de Estado',
            },
        ),
    ]
